#!/bin/bash

# This script sets up the environment and runs gem5 experiments in parallel using SLURM.


echo "Setting up experiment directories and scripts for only SLURM."
echo "Please note that the generated results might have small differences compared to the results generated by the containerized setup."

# Ensure we are in the gem5 directory
if [ "$(basename "$PWD")" != "gem5" ]; then
    echo "Changing to gem5 directory"
    cd gem5 || { echo "Failed to change directory to gem5"; exit 1; }
fi


if ! uv run python3 result-scripts/setup_test.py -s; then
    echo "Error: Setup failed"
    exit 1
fi

echo "Running gem5 experiments in parallel"
if ! uv run python3 result-scripts/execute_run_script.py -s; then
    echo "Error: Execution failed"
    exit 1
fi

echo "Experiments scheduled successfully. Now please wait for the results to be generated."