Frontend:
  impl: GEM5
  clock_ratio: 8

MemorySystem:
  impl: BHDRAMSystem
  clock_ratio: 3

  DRAM:
    impl: DDR5-VRR
    org:
      preset: DDR5_16Gb_x8
      channel: 1
      rank: 2
    timing:
      preset: DDR5_3200AN 
    RFM:
      BRC: 2

  BHDRAMController:
    impl: BHDRAMController
    BHScheduler:
      impl: BHScheduler
    RefreshManager:
      impl: DelayedRefresh
      max_delays: 2
    RowPolicy:
      impl: ClosedRowPolicy
      cap: 16
    plugins:
      - ControllerPlugin:
          impl: RFMManager
          rfm_thresh: 40
      # - ControllerPlugin:
      #     impl: SideChannelHelper

  AddrMapper:
    impl: RoBaRaCoCh_with_rit
